In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna() #Not Available

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data = pd.Series(["a", np.nan, None, "d"])
string_data
string_data.isna()


0    False
1     True
2     True
3    False
dtype: bool

In [5]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [6]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna() #drop not available: nan 값 지우는 것

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
pd.DataFrame(data)

0
0  1.0
1  NaN
2  3.5
3  NaN
4  7.0

In [8]:
data.notna()

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [9]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data
data.dropna()

#행 값들 중 하나라도 비면 drop

0    1    2
0  1.0  6.5  3.0

In [11]:
data.dropna(how="all") # 전부다 비어야 drop 한다.

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[4] = np.nan
data
#data.dropna(axis="columns", how="all")
data.dropna(axis="columns")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [13]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df

0         1         2
0  1.184211 -1.146024 -0.123338
1  0.546024 -0.330838  1.209197
2  1.549762  0.283253 -1.231397
3  1.004344 -0.844374  0.109790
4  0.903598  0.602399 -0.233321
5  0.927881 -0.078748 -1.104545
6 -0.921467 -0.559308  0.074805

In [14]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  1.184211       NaN       NaN
1  0.546024       NaN       NaN
2  1.549762       NaN -1.231397
3  1.004344       NaN  0.109790
4  0.903598  0.602399 -0.233321
5  0.927881 -0.078748 -1.104545
6 -0.921467 -0.559308  0.074805

In [15]:
df_d=df.dropna(thresh=2)
df_d

0         1         2
2  1.549762       NaN -1.231397
3  1.004344       NaN  0.109790
4  0.903598  0.602399 -0.233321
5  0.927881 -0.078748 -1.104545
6 -0.921467 -0.559308  0.074805

In [16]:
df_f=df.fillna(0)
df_f

0         1         2
0  1.184211  0.000000  0.000000
1  0.546024  0.000000  0.000000
2  1.549762  0.000000 -1.231397
3  1.004344  0.000000  0.109790
4  0.903598  0.602399 -0.233321
5  0.927881 -0.078748 -1.104545
6 -0.921467 -0.559308  0.074805

In [17]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  1.184211  0.500000  0.000000
1  0.546024  0.500000  0.000000
2  1.549762  0.500000 -1.231397
3  1.004344  0.500000  0.109790
4  0.903598  0.602399 -0.233321
5  0.927881 -0.078748 -1.104545
6 -0.921467 -0.559308  0.074805

In [18]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0 -0.384796 -0.964631  0.784723
1 -0.555471  1.592917 -1.486280
2 -1.117355       NaN  0.476325
3 -0.870746       NaN  0.716416
4  0.183322       NaN       NaN
5 -0.001607       NaN       NaN

In [19]:
df.fillna(method="ffill")
df_fill=df.fillna(method="ffill", limit=2)
df_fill

0         1         2
0 -0.384796 -0.964631  0.784723
1 -0.555471  1.592917 -1.486280
2 -1.117355  1.592917  0.476325
3 -0.870746  1.592917  0.716416
4  0.183322       NaN  0.716416
5 -0.001607       NaN  0.716416

In [20]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [21]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [22]:
data.duplicated() #인덱스 중복이면 True 중복아니면 False 

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [23]:
df_drop=data.drop_duplicates()
pd.DataFrame(df_drop)

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [24]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
data["v1"] = range(7)
data
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [26]:
data.drop_duplicates(["k1", "k2"], keep="last") #둘 다 중복 일 경우만 drop 

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [27]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [29]:
data["animal"] = data["food"].map(meat_to_animal) #food와 대응되는 값을 map해서 animal이라는 컬럼으로 추가
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [30]:
def get_animal(x):
    return meat_to_animal[x]
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [31]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [32]:
data.replace(-999, np.nan) ## 특정한 값을 지정한 값으로 대체

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [33]:
data.replace([-999, -1000], np.nan) #두개도 가능

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [34]:
data.replace([-999, -1000], [np.nan, 0]) #대응되는 값으로도 가능 -999 는 nan으로 -1000 은 0 으로 대체

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [35]:
data.replace({-999: np.nan, -1000: 0}) #위와 같은 방법

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [36]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [37]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [38]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [39]:
data.rename(index=str.title, columns=str.upper) #이름 갱신

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [40]:
data.rename(index={"OHIO": "INDIANA"}, #이름 수정
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [41]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] #cut을 통해 범주화 할 대상
bins = [18, 25, 35, 60, 100]                            #범주화의 기준 [18,25) --> ages가 이 범위면 age_categories에 들어감 
labels=['a','b','c','d']                                #label을 정하면 그 라벨이 age_categories에 들어감 
age_categories = pd.cut(ages, bins,labels=labels)                     
age_categories[:10]

['a', 'a', 'a', 'b', 'a', 'a', 'c', 'b', 'd', 'c']
Categories (4, object): ['a' < 'b' < 'c' < 'd']

In [42]:
print(age_categories.codes)
print(age_categories.categories)
print(age_categories.categories[0])
pd.value_counts(age_categories)

[0 0 0 1 0 0 2 1 3 2 2 1]
Index(['a', 'b', 'c', 'd'], dtype='object')
a


a    5
b    3
c    3
d    1
dtype: int64

In [43]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [44]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [45]:
data = np.random.uniform(size=20)
pd.cut(data, 4, precision=2)

[(0.28, 0.49], (0.71, 0.92], (0.71, 0.92], (0.71, 0.92], (0.28, 0.49], ..., (0.28, 0.49], (0.49, 0.71], (0.71, 0.92], (0.71, 0.92], (0.065, 0.28]]
Length: 20
Categories (4, interval[float64, right]): [(0.065, 0.28] < (0.28, 0.49] < (0.49, 0.71] < (0.71, 0.92]]

In [46]:
data = np.random.standard_normal(1000)
data

array([ 4.48815856e-01, -3.52548646e-02, -1.22863499e+00,  8.91585952e-01,
        5.60354483e-01,  9.83834036e-01,  5.64784933e-03, -1.30230009e+00,
        4.86959074e-01, -7.24184342e-01,  2.55508605e+00,  3.29398024e-01,
       -1.40124792e+00,  1.77475798e-01, -1.02091289e+00,  2.89567218e-01,
        5.37063500e-01, -1.12101462e+00,  3.46779751e-01, -3.90942307e-01,
       -7.73580915e-01,  9.63722378e-01, -5.86932702e-01,  5.79417596e-01,
        2.40012380e-01,  6.67487836e-01,  1.10841130e+00, -1.56544837e-01,
       -1.22048006e+00,  5.49356400e-01,  7.88331534e-01, -9.43089520e-01,
       -7.40500332e-01, -1.90172947e-01,  7.31044374e-01, -1.86469031e-01,
       -1.05549755e+00, -6.07993966e-01,  1.54496978e+00,  1.66000647e+00,
       -7.62496285e-01, -6.89080666e-01,  1.41193672e+00, -9.14369048e-01,
        9.06693224e-01,  8.47546629e-01, -2.92718608e-02, -8.28422437e-01,
        1.13825450e+00,  1.41227096e-01,  1.56983330e-01, -2.48205522e+00,
        3.19192513e-01,  

In [47]:
quartiles = pd.qcut(data, 4, precision=2)               #quarter cut 4개 범주로 나눈다.
quartiles
pd.value_counts(quartiles)

(-3.17, -0.61]    250
(-0.61, 0.082]    250
(0.082, 0.72]     250
(0.72, 2.84]      250
dtype: int64

In [48]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.1639999999999997, -1.129]    100
(-1.129, 0.082]                  400
(0.082, 1.284]                   400
(1.284, 2.836]                   100
dtype: int64

In [49]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018943    -0.029426    -0.036563    -0.006634
std       0.968079     0.980054     1.005536     0.970159
min      -3.259784    -3.108208    -3.124487    -3.248197
25%      -0.653766    -0.672407    -0.732675    -0.618099
50%       0.030705    -0.049300    -0.037105    -0.020129
75%       0.671830     0.653957     0.683988     0.626911
max       3.371516     2.864219     2.821838     3.501122

In [50]:
col = data[2]                         #3번째 컬럼에서 절대값 3이 넘는 값과 인덱스 출력
col[col.abs() > 3]

45    -3.045460
246   -3.124487
527   -3.044446
Name: 2, dtype: float64

In [51]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
8    3.371516 -1.499469 -1.088591  0.321886
45   0.320780  0.869931 -3.045460  0.043313
246  0.837017 -1.272104 -3.124487 -0.429475
274 -3.259784  0.266025 -2.077967 -1.510862
350 -1.006112  1.196316 -0.539068  3.501122
527 -1.660540 -0.545524 -3.044446  0.054046
883 -2.352070  2.539077  0.849932 -3.248197
905 -2.205616 -3.108208  0.545110  0.554660
938 -0.210903 -0.344303  1.226982  3.316124
996 -0.619131 -0.285780 -0.300210 -3.066618

In [52]:
data[(data.abs() > 3).any(axis=1)]

0         1         2         3
8    3.371516 -1.499469 -1.088591  0.321886
45   0.320780  0.869931 -3.045460  0.043313
246  0.837017 -1.272104 -3.124487 -0.429475
274 -3.259784  0.266025 -2.077967 -1.510862
350 -1.006112  1.196316 -0.539068  3.501122
527 -1.660540 -0.545524 -3.044446  0.054046
883 -2.352070  2.539077  0.849932 -3.248197
905 -2.205616 -3.108208  0.545110  0.554660
938 -0.210903 -0.344303  1.226982  3.316124
996 -0.619131 -0.285780 -0.300210 -3.066618

In [53]:
data[(data.abs()>3)].count()

0    2
1    1
2    3
3    4
dtype: int64

In [54]:
np.sign(data) #np.sign 양수이면 1 음수면 -1, 0이면 0으로 만들어준다.

0    1    2    3
0   -1.0 -1.0 -1.0  1.0
1    1.0 -1.0 -1.0 -1.0
2    1.0 -1.0  1.0  1.0
3   -1.0  1.0  1.0  1.0
4   -1.0 -1.0  1.0  1.0
..   ...  ...  ...  ...
995  1.0  1.0  1.0 -1.0
996 -1.0 -1.0 -1.0 -1.0
997  1.0  1.0 -1.0  1.0
998 -1.0  1.0  1.0  1.0
999  1.0 -1.0 -1.0 -1.0

[1000 rows x 4 columns]

In [55]:
data[data.abs() > 3] = np.sign(data) * 3 
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018831    -0.029318    -0.036348    -0.007137
std       0.966015     0.979719     1.004893     0.966429
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.653766    -0.672407    -0.732675    -0.618099
50%       0.030705    -0.049300    -0.037105    -0.020129
75%       0.671830     0.653957     0.683988     0.626911
max       3.000000     2.864219     2.821838     3.000000

In [56]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0 -1.0  1.0
1  1.0 -1.0 -1.0 -1.0
2  1.0 -1.0  1.0  1.0
3 -1.0  1.0  1.0  1.0
4 -1.0 -1.0  1.0  1.0

In [59]:
sampler = np.random.permutation(5)
sampler

array([4, 2, 1, 0, 3])

In [62]:
column_sampler = np.random.permutation(7)                    #표로 출력 컬럼은 permutation 숫자로 랜덤순서로 생김  
column_sampler
df.take(column_sampler, axis=1)

3   1   2   6   4   0   5
0   3   1   2   6   4   0   5
1  13  11  12  16  14  10  15
2  23  21  22  26  24  20  25
3  33  31  32  36  34  30  35

In [63]:
column_sampler = np.random.permutation(10)                     
column_sampler
df.take(column_sampler, axis=1)

1   3   6   0   5   2   8   4   7   9
0   1   3   6   0   5   2   8   4   7   9
1  11  13  16  10  15  12  18  14  17  19
2  21  23  26  20  25  22  28  24  27  29
3  31  33  36  30  35  32  38  34  37  39

In [70]:
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39

In [71]:
df.sample(n=2)

0   1   2   3   4   5   6   7   8   9
2  20  21  22  23  24  25  26  27  28  29
1  10  11  12  13  14  15  16  17  18  19

In [72]:
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n=10, replace=True)

3    6
3    6
3    6
2   -1
1    7
4    4
0    5
4    4
3    6
1    7
dtype: int64

In [74]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df


key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [75]:
pd.get_dummies(df["key"]) #key값들이 컬럼이 되어 표 재구성

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [77]:
dummies = pd.get_dummies(df["key"], prefix="Key")           #prefix가 앞에 붙어 컬럼명이 설정됨
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  Key_a  Key_b  Key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [78]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [79]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [80]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [81]:
np.random.seed(12345) # 반복을 위해서 시드 설정
values = np.random.uniform(size=10)
values
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [82]:
s = pd.Series([1, 2, 3, None])
s
s.dtype

dtype('float64')

In [84]:
s[3]
s[3] is pd.NA

True

In [ ]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [ ]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

In [85]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
df
df["A"] = df["A"].astype("Int64") #type 변경
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [86]:
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [87]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [88]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [89]:
"::".join(pieces)

'a::b::guido'

In [90]:
"guido" in val
val.index(",")
val.find(":")

-1

In [91]:
val.count(",")

2

In [92]:
val.replace(",", "::")
val.replace(",", "")

'ab  guido'

In [94]:
import re
text = "foo    bar\t baz  \tqux"
re.split(r"\s+", text)                  #탭 스페이스바 같은 공백 제거

['foo', 'bar', 'baz', 'qux']

In [95]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [96]:
regex.findall(text)

['    ', '\t ', '  \t']

In [97]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE) #규칙

In [98]:
regex.findall(text) #규칙에 맞는 것 찾기

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [101]:
m = regex.search(text)
m
#text[m.start():m.end()]

<re.Match object; span=(5, 20), match='dave@google.com'>


In [ ]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [104]:
m = regex.match("wesm@bright.net")
m.groups()

()

In [105]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [ ]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

In [106]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [107]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [108]:
data_as_string_ext = data.astype('string')
data_as_string_ext
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [109]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [110]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [111]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [112]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [116]:
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
print(values)
pd.unique(values)
pd.value_counts(values)

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object


apple     6
orange    2
dtype: int64

In [118]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
print(values)
dim

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64


0     apple
1    orange
dtype: object

In [119]:
dim.take(values) #values 값으로 dim의 값 추출하는 것

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [120]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [121]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [122]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [123]:
c.categories
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [124]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [125]:
df['fruit'] = df['fruit'].astype('category')
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [126]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [127]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [128]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [129]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [130]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [131]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [132]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [133]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [134]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [135]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [136]:
categories = labels.astype('category')

In [138]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [139]:
cat_s.cat.codes
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [140]:
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [141]:
cat_s.value_counts()
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [142]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [143]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [144]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1